name: Build and Release

on:
  workflow_dispatch:
  push:
    tags: [ "v*.*.*" ] 

jobs:
  build_release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output publish/ConvertCase

    - name: Create ZIP
      run: Compress-Archive -Path "publish/ConvertCase" -DestinationPath "ConvertCase.zip"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        prerelease: false
        files: ConvertCase.zip
        token: ${{ secrets.GITHUB_TOKEN }}