name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ] 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ConvertCase
        path: publish/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ConvertCase

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: false
        files: |
          ConvertCase/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}